language: python
python:
- '3.7'
services:
- redis
before_install:
- python$PY -m pip install Cython
- python$PY -m pip install numpy
- python$PY -m pip install -U pip
- python$PY --version
- python$PY -m cython --version
- python$PY -c "import numpy;print(numpy.__version__)"
install:
- pip install .[funcx]
script:
- pip install -r test-requirements.txt
- flake8 colmena/
- pytest colmena
deploy:
  provider: pypi
  user: __token__
  skip_existing: true
  distributions: sdist bdist_wheel
  password:
    secure: I4qRLn7e8mSB5xcy8IPOMA4RB6izhNmyRkzK/lpEBMDzdsu/gPmpxl9xkhOn2yjGYbwIdg08rIq4629vGZeDxPnRpPoYMVnBwZmi780oxN9PpmxAld2SEjL/pUXE00G9oWsOpO0Qh2+rPYDIoXOtZr75wkMnQsqyLyI5EiDN8A/KQqip4yEISkNcV7zyJo5aMq21gA2wbsq73xwmWYQnvr7N3JrYE7peJxvFSWxRzpLWHtuzIQpTF5yPo+JL6wQGAtzx9kA3J3IChaYRK9I6gNI+FvOfCLqMa63ubw+gvukry2tTqwzaWFLfnCI+AMraFzLTKm74DEH1FV5+9cBrEY0N94Isodgt/4BZ+e2prmqIDaOZrhwmUepmjf/pgRowoMh91RT73+iNhllwfbpK/+Ed+fZh4/xTM70+iHuoRy7BqX906ILlEcaa5gvAYBxwHDyazoIrpoxjJq4hRLfAxPoGXRSkEp0rA3E+DbLnNkPwcZ3ieNKO2xA1EbSLyb369/moG6/sj/fBi5pMPomDC8MtyjfkKVdSeVYSl5ZyVgW1si4ff+6AKZ9C8yJLlmtCgSEMRHTlS6+oqZMIcdnsIWjmwJ3F0JDqpkHi3n/Jk9pdmPnGuqbCEWeUgIqUR9Tl8tCTVs2rBK5L5gVwVvfi71FXy3nTVQREr+gSfQRyYfg=
  on:
    tags: true
    branch: master
