name: colmena
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.*
  - scikit-learn==0.22.*
  - redis==5.0.*
  - redis-py==3.4.*
  - psutil
  - sphinx
  - sphinx_rtd_theme
  - jupyterlab
  - pytest-timeout
  - pytest
  - flake8
  - pip
  - pip:
      - -e .
      - parsl>=1.*
      - pydantic
      - proxystore==0.2.*
